# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cddc26a82adcd5dd017e951d41663e919d0fcc5f16167d8325d51cf9cfc53c0c65f108829245477f6e6f4efbf01c3fa9b4df8ea86fb95331c85fc2ced3634a39

test:
  secret_key_base: 824ff17d48b4637c20bc51965d302464bc3bf0f1918375fe36e15262ab024870ae40f8123b9865904a51b22ee02ee7ff6af18846110b8e4c0875fc9ab5ad0c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
